spring.application.name=Guardrails
spring.datasource.url=jdbc:mysql://localhost:3306/assignmentdb
spring.datasource.username=root
spring.datasource.password=Root
spring.jpa.hibernate.ddl-auto=update
spring.data.show-sql=true
spring.data.redis.host=localhost
spring.data.redis.port=6379
server.port=8080